runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  ATLAS_URI: 'mongodb+srv://karanvsingh:hello123@cluster0.efpso.gcp.mongodb.net/DubHacks2020?retryWrites=true&w=majority'